### ISSUE TITLE
关于源代码中的若干问题

### ISSUE THREAD

**Issue by ghost** [DrkCore/CoreDemo#1]
楼主你好，在你的代码里发现3个问题，OverWatchView类中发现这样的代码：
        anim[0].addUpdateListener(animation -> 
        {
            outAngel_1 = (float) animation.getAnimatedValue();
            invalidate();
        });
请问这个箭头->  是什么意思呢？你是用QT创建的项目吗？

**Comment by OneLiteCore** [comment]
Lambda表达式
